## Scaling

In [2]:
import pandas as pd
import numpy as np
from numpy import set_printoptions
from sklearn import preprocessing

In [9]:
data= pd.read_csv(r'C:\Users\rachi\Desktop\Machine Learninng\Book Exercise\pima-indians-diabetes.csv')

In [10]:
data.columns

Index(['Preg', 'Plas', 'Pres', 'Skin', 'Test', 'Mass', 'Pedi', 'Age', 'Class'], dtype='object')

In [12]:
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_rescaled = data_scaler.fit_transform(data)

In [14]:
set_printoptions(precision=1)
print(data_rescaled[0:10])

[[0.4 0.7 0.6 0.4 0.  0.5 0.2 0.5 1. ]
 [0.1 0.4 0.5 0.3 0.  0.4 0.1 0.2 0. ]
 [0.5 0.9 0.5 0.  0.  0.3 0.3 0.2 1. ]
 [0.1 0.4 0.5 0.2 0.1 0.4 0.  0.  0. ]
 [0.  0.7 0.3 0.4 0.2 0.6 0.9 0.2 1. ]
 [0.3 0.6 0.6 0.  0.  0.4 0.1 0.2 0. ]
 [0.2 0.4 0.4 0.3 0.1 0.5 0.1 0.1 1. ]
 [0.6 0.6 0.  0.  0.  0.5 0.  0.1 0. ]
 [0.1 1.  0.6 0.5 0.6 0.5 0.  0.5 1. ]
 [0.5 0.6 0.8 0.  0.  0.  0.1 0.6 1. ]]


## Normalization

### L1 Normalization

In [15]:
data= pd.read_csv(r'C:\Users\rachi\Desktop\Machine Learninng\Book Exercise\pima-indians-diabetes.csv')

In [19]:
from sklearn.preprocessing import Normalizer
Data_normalizer = Normalizer(norm='l1').fit(data)
Data_normalized = Data_normalizer.transform(data)

In [21]:
set_printoptions(precision=2)
Data_normalized[0:3]

array([[0.02, 0.43, 0.21, 0.1 , 0.  , 0.1 , 0.  , 0.14, 0.  ],
       [0.  , 0.36, 0.28, 0.12, 0.  , 0.11, 0.  , 0.13, 0.  ],
       [0.03, 0.59, 0.21, 0.  , 0.  , 0.07, 0.  , 0.1 , 0.  ]])

## Binarization

In [25]:
from sklearn.preprocessing import Binarizer
binarizer= Binarizer(threshold=0.5).fit(data)
Binarized_data= binarizer.transform(data)
Binarized_data[0:3]

array([[1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 0., 0., 1., 1., 1., 1.]])

## Standardization

In [28]:
from sklearn.preprocessing import StandardScaler
standard_scaler= StandardScaler().fit(data)
data_rescaled=standard_scaler.transform(data)
data_rescaled[0:5]

array([[ 0.64,  0.85,  0.15,  0.91, -0.69,  0.2 ,  0.47,  1.43,  1.37],
       [-0.84, -1.12, -0.16,  0.53, -0.69, -0.68, -0.37, -0.19, -0.73],
       [ 1.23,  1.94, -0.26, -1.29, -0.69, -1.1 ,  0.6 , -0.11,  1.37],
       [-0.84, -1.  , -0.16,  0.15,  0.12, -0.49, -0.92, -1.04, -0.73],
       [-1.14,  0.5 , -1.5 ,  0.91,  0.77,  1.41,  5.48, -0.02,  1.37]])